FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY ./scripts ./scripts/ 
COPY ./data ./data
COPY python-starter.sh ./

RUN chmod +x /app/python-starter.sh

CMD [ "/bin/bash", "/app/python-starter.sh" ]

