services:

  mariadb:
    image: mariadb:11.6
    container_name: mariadb-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_USER: mert
      MYSQL_PASSWORD: 44444444
      MYSQL_ROOT_PASSWORD: 44444444
    volumes:
      - ./volumes/maria_data:/var/lib/mysql
    networks:
      dahbest:
        ipv4_address: 172.80.0.30
        
  mongodb:
    image: mongo:8.0
    restart: always
    container_name: mongodb-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mert
      MONGO_INITDB_ROOT_PASSWORD: 4444
    volumes:
      - ./volumes/mongo_data:/data/db
    networks:
      dahbest:
        ipv4_address: 172.80.0.31

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-container
    restart: always
    depends_on:
      - mariadb
      - mongodb
    networks:
      dahbest:
        ipv4_address: 172.80.0.32

networks:
  dahbest:
    external: true
    
volumes:
  maria_data:
  mongo_data: