FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    openssh-server \ 
    openssh-client && \
    apt-get clean

# SSH configuration
RUN mkdir -p /var/run/sshd
RUN echo 'root:mertmert' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Generate SSH keys
RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -N ""
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY ./scripts ./scripts/ 
COPY ./data ./data
COPY python-starter.sh ./

RUN chmod +x /app/python-starter.sh

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]

