version: '3.8'

services:

  mariadb:
    image: mariadb:11.6
    container_name: mariadb-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mert
      MYSQL_PASSWORD: 4444
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    volumes:
      - ./volumes/maria_data:/var/lib/mysql
    networks:
      dahbest:
        aliases:
          - mariadb-container
        ipv4_address: 172.28.0.2
        
  mongodb:
    image: mongo:8.0
    restart: always
    container_name: mongodb-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mert
      MONGO_INITDB_ROOT_PASSWORD: 4444
    volumes:
      - ./volumes/mongo_data:/data/db
    networks:
      dahbest:
        aliases:
          - mongodb-container
        ipv4_address: 172.28.0.3 

  python-app:
    build: .
    container_name: python-container
    restart: always
    depends_on:
      - mariadb
      - mongodb
    networks:
      dahbest:
        ipv4_address: 172.28.0.4

networks:
  dahbest:
    name: dahbest 
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
    
volumes:
  maria_data:
  mongo_data: