version: '3.8'

services:
  mongodb:
    image: mongo 
    restart: always
    container_name: mongodb-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mert
      MONGO_INITDB_ROOT_PASSWORD: 4444
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: