version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mert
      MYSQL_PASSWORD: 4444
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    volumes:
      - ./maria_data:/var/lib/mysql

volumes:
  maria_data: